package com.coop.milk.services;

import com.coop.milk.models.Farmer;
import com.coop.milk.models.MonthlyStatement;
import com.coop.milk.repositories.FarmerRepository;
import com.coop.milk.repositories.MonthlyStatementRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ReportGeneratorService {

    @Autowired
    private MonthlyStatementRepository statementRepository;
    
    @Autowired
    private FarmerRepository farmerRepository;

    @Autowired
    private NotificationService notificationService;
    
    /**
     *  THE AUTOMATION ENGINE:
     * "0 * * * * ?" -> TEST MODE: Runs every 1 minute for your university presentation.
     * "0 0 0 1 * ?" -> PRODUCTION MODE: Runs at 00:00 (Midnight) on the 1st day of every month.
     */
    @Scheduled(cron = "0 0 0 1 * ?") //Change this back to "0 0 0 1 * ?" after your presentation!
    @Transactional
    public void generateOfficialMonthlyReports() {
        // Calculate the month that just finished
        LocalDate lastMonth = LocalDate.now().minusMonths(1);
        String targetMonth = lastMonth.format(DateTimeFormatter.ofPattern("MMM-yyyy")).toUpperCase();
        
        System.out.println("CRON INITIATED: Generating official end-of-month reports for " + targetMonth);
        
        List<Farmer> allFarmers = farmerRepository.findAll(); 
        
        for (Farmer farmer : allFarmers) {
            // Mock totals for the prototype
            double totalLiters = Math.floor(Math.random() * (1200 - 400 + 1) + 400); 
            double totalPayout = totalLiters * 45.00; 
            
            // isDraft is now permanently FALSE. 
            MonthlyStatement statement = new MonthlyStatement(
                farmer.getFarmerNumber(),
                "SYSTEM_AUTO", // Generated by the system, not a manager
                targetMonth,
                totalLiters,
                totalPayout,
                false 
            );
            statementRepository.save(statement);

            // Dispatch the automated SMS to the farmer
            if (farmer.getPhoneNumber() != null && !farmer.getPhoneNumber().isEmpty()) {
                notificationService.sendMonthlyStatementSms(
                    farmer.getPhoneNumber(), 
                    farmer.getFullName(), 
                    targetMonth, 
                    totalLiters, 
                    totalPayout
                );
            }
        }
        System.out.println("✅ End-of-month processing complete. SMS notifications dispatched.");
    }
}