package com.coop.milk.services;

import com.coop.milk.models.Farmer;
import com.coop.milk.models.MilkDelivery;
import com.coop.milk.models.MonthlyStatement;
import com.coop.milk.repositories.FarmerRepository;
import com.coop.milk.repositories.MilkDeliveryRepository;
import com.coop.milk.repositories.MonthlyStatementRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.YearMonth;
import java.time.format.DateTimeFormatter;
import java.util.List;

@Service
public class ReportGeneratorService {

    @Autowired
    private MonthlyStatementRepository statementRepository;
    
    @Autowired
    private FarmerRepository farmerRepository;

    // 💡 NEW: We need the Delivery Repository to pull the real milk records
    @Autowired
    private MilkDeliveryRepository deliveryRepository; 

    @Autowired
    private NotificationService notificationService;
    
    /**
     * THE AUTOMATION ENGINE:
     * "0 * * * * ?" -> TEST MODE: Runs every 1 minute.
     * "0 0 0 1 * ?" -> PRODUCTION MODE: Runs at 00:00 (Midnight) on the 1st day of every month.
     */
    @Scheduled(cron = "0 0 0 1 * ?") 
    @Transactional
    public void generateOfficialMonthlyReports() {
        // Calculate the month that just finished
        LocalDate lastMonthDate = LocalDate.now().minusMonths(1);
        String targetMonthStr = lastMonthDate.format(DateTimeFormatter.ofPattern("MMM-yyyy")).toUpperCase();
        YearMonth targetYearMonth = YearMonth.from(lastMonthDate); // Used for exact date matching
        
        System.out.println("CRON INITIATED: Generating REAL end-of-month reports for " + targetMonthStr);
        
        List<Farmer> allFarmers = farmerRepository.findAll(); 
        
        for (Farmer farmer : allFarmers) {
            
            // 1. Fetch ALL deliveries for this specific farmer
            List<MilkDelivery> deliveries = deliveryRepository.findByFarmer_FarmerNumberOrderByDeliveryDateAsc(farmer.getFarmerNumber());
            
            double totalLiters = 0.0;
            double totalPayout = 0.0;

            // 2. Loop through deliveries and ONLY add up the ones from last month
            for (MilkDelivery d : deliveries) {
                YearMonth deliveryMonth = YearMonth.from(d.getDeliveryDate());
                
                if (deliveryMonth.equals(targetYearMonth)) {
                    totalLiters += d.getQuantityLiters().doubleValue();
                    
                    // Safely extract the payout 
                    if (d.getTotalPayout() != null) {
                        totalPayout += d.getTotalPayout().doubleValue();
                    } else if (d.getPricePerLiter() != null) {
                        totalPayout += (d.getQuantityLiters().doubleValue() * d.getPricePerLiter().doubleValue());
                    }
                }
            }

            // 3. ONLY generate a report if the farmer actually delivered milk this month!
            if (totalLiters > 0) {
                MonthlyStatement statement = new MonthlyStatement(
                    farmer.getFarmerNumber(),
                    "SYSTEM_AUTO", // Generated by the system, not a manager
                    targetMonthStr,
                    totalLiters,
                    totalPayout,
                    false 
                );
                statementRepository.save(statement);

                // Dispatch the automated SMS to the farmer
                if (farmer.getPhoneNumber() != null && !farmer.getPhoneNumber().isEmpty()) {
                    notificationService.sendMonthlyStatementSms(
                        farmer.getPhoneNumber(), 
                        farmer.getFullName(), 
                        targetMonthStr, 
                        totalLiters, 
                        totalPayout
                    );
                }
            }
        }
        System.out.println("Real End-of-month processing complete. SMS notifications dispatched.");
    }
}